WindowManager:
    MainWindow:
    FirstMain:


<MainWindow>:
    name: 'main'

    GridLayout:
        cols: 2

        Label:
            text: 'Password: '

        TextInput:
            id: pasw
            multiline: False

    Button:
        text: 'Submit'
        on_release:
            app.root.current = 'first'

<FirstMain>:
    name: 'first'

    Button:
        text: 'Go back'
        on_release:
            app.root.current = 'main'

